/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_santiago_catbox_NDK_TestNDK */

#include <android/log.h>
#include <string.h>

#define   LOG_TAG    "LOG_TEST"
#define   LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
#define   LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)

#ifndef _Included_com_santiago_catbox_NDK_TestNDK
#define _Included_com_santiago_catbox_NDK_TestNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_santiago_catbox_NDK_TestNDK
 * Method:    ndkReturnHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_santiago_catbox_NDK_TestNDK_ndkReturnHelloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
